# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='course.proto',
  package='discudemy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x63ourse.proto\x12\tdiscudemy\"-\n\x07\x43ourses\x12\"\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x11.discudemy.Course\"#\n\x06\x43ourse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\tb\x06proto3'
)




_COURSES = _descriptor.Descriptor(
  name='Courses',
  full_name='discudemy.Courses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='courses', full_name='discudemy.Courses.courses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=72,
)


_COURSE = _descriptor.Descriptor(
  name='Course',
  full_name='discudemy.Course',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='discudemy.Course.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='discudemy.Course.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)

_COURSES.fields_by_name['courses'].message_type = _COURSE
DESCRIPTOR.message_types_by_name['Courses'] = _COURSES
DESCRIPTOR.message_types_by_name['Course'] = _COURSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Courses = _reflection.GeneratedProtocolMessageType('Courses', (_message.Message,), {
  'DESCRIPTOR' : _COURSES,
  '__module__' : 'course_pb2'
  # @@protoc_insertion_point(class_scope:discudemy.Courses)
  })
_sym_db.RegisterMessage(Courses)

Course = _reflection.GeneratedProtocolMessageType('Course', (_message.Message,), {
  'DESCRIPTOR' : _COURSE,
  '__module__' : 'course_pb2'
  # @@protoc_insertion_point(class_scope:discudemy.Course)
  })
_sym_db.RegisterMessage(Course)


# @@protoc_insertion_point(module_scope)
